### PR TITLE
Initial implementation of deterministic sampling in Voronoi grids.

### PR DESCRIPTION
**Pull request by bluescarni**

### CODE REVIEW

**Comment by bluescarni** [comment]
@astrofrog Two builds fail, it seems like a problem with ``libpng``. Any idea on how to fix it?

**Comment by astrofrog** [comment]
@bluescarni - can you rebase this? I think I fixed the issue in master.

**Comment by astrofrog** [comment]
@bluescarni - just a reminder, can you rebase this? Thanks!

**Comment by astrofrog** [comment]
Since @koepferl needs this today, I'll go ahead and rebase manually and open another PR to make sure the tests pass.

**Pull request closed without merging**
